window.MEMO=function(){var f={xa:function(){return Math.random().toString(36).replace(/[^a-z]+/g,"")},Y:function(a){for(var b=[],c=/-|\//,d=[/\d{4}\/\d{1,2}\/\d{1,2}/,/\d{4}-\d{1,2}-\d{1,2}/,/20\d{6}/],e=0;e<d.length;e++){var h=a.match(d[e]);if(null!=h)return a=h[0],a.match(c)?b=a.split(c):(b[0]=a.substring(0,4),b[1]=a.substring(4,6),b[2]=a.substring(6,8)),new Date(b[0],b[1]-1,b[2])}},i:function(a){return Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},log:function(a){window.console&&
console.log(a)},oa:function(a){return"[object String]"===Object.prototype.toString.call(a)},G:function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b},sa:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a},contains:function(a,b){return-1!==(a.join(",")+",").indexOf(b+",")},Ga:function(a,b){if(!isNaN(b)&&!this.oa(b))for(var c=0;c<=a.length;c++)if(a[c]===b)return!0;return!1},A:function(a){"string"===typeof a&&(a=a.split(","));if(this.i(a)){for(var b=0;b<a.length;b+=
1)"string"===typeof a[b]&&(a[b]=a[b].replace(/^\s*/,"").replace(/\s*$/,"").replace(/\|/,""));return a.join("|")}},h:function(){},N:function(){return window.location.protocol+"//"},va:[25,50,75,100]},x={encode:function(a,b){var c=[];if(f.i(a))for(var d=0,e;d<a.length;d+=1)e=a[d],/\[\]$/.test(b)?c.push(encodeURIComponent(b)+"="+encodeURIComponent(e)):c.push(this.encode(e,b+"["+("object"===typeof e?d:"")+"]"));else if("object"!==typeof a||null===a||"nodeType"in a)c.push(encodeURIComponent(b)+"="+encodeURIComponent(a));
else for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&(b?c.push(this.encode(a[d],b+"["+d+"]")):c.push(this.encode(a[d],d)));return c.join("&")}},k={M:!1,info:f.h,error:f.log,b:function(){window.SPR_DEBUG&&(this.M=!0,window.SPR_DEBUG.info&&(this.info=window.SPR_DEBUG.info),window.SPR_DEBUG.error&&(this.error=window.SPR_DEBUG.error))},reset:function(){this.M=!1;this.info=f.h;this.info=f.log},Ba:function(a){var b=document.createElement("img");b.src=f.N()+"elsa.memoinsights.com/pixel?bad=true&error="+a.message;
b.setAttribute("width","1px");document.body?document.body.appendChild(b):document.head.appendChild(b)},Ca:function(a){"info"===a?this.error=this.info=f.log:"error"===a?(this.info=f.h,this.error=f.log):this.error=this.info=f.h}},g={H:0,g:{x:0,y:0},isVisible:!0,b:function(){function a(){d.isVisible=document[e]?!1:!0}function b(){d.flush();window.removeEventListener("DOMContentLoaded",b,!1)}function c(){d.ready&&(document.detachEvent("onreadystatechange",c),m&&(m=!1,d.flush()))}var d=this;d.H=0;this.ta(window,
"mousemove",function(p){d.g={x:p.clientX,y:p.clientY}});if("undefined"!==typeof document.hidden){var e="hidden";var h="visibilitychange"}else"undefined"!==typeof document.mozHidden?(e="mozHidden",h="mozvisibilitychange"):"undefined"!==typeof document.msHidden?(e="msHidden",h="msvisibilitychange"):"undefined"!==typeof document.webkitHidden&&(e="webkitHidden",h="webkitvisibilitychange");"undefined"!==typeof document.addEventListener&&"undefined"!==typeof e&&document.addEventListener(h,a,!1);var m=!0;
window.addEventListener?window.addEventListener("DOMContentLoaded",b,!1):document.attachEvent&&document.attachEvent("onreadystatechange",c)},ba:function(){return this.a(this,"property","og:url")},$:function(){return this.ha(this,"canonical")},da:function(){return this.a(this,"name","twitter:url")},fa:function(){return window.location.protocol+"//"+window.location.hostname+window.location.pathname},ea:function(){var a=this.$()||this.ba()||this.da()||this.fa();return f.i(a)?a[0]:a},aa:function(){var a=
this.a(this,"property","article:sr_published_at")||this.a(this,"name","pubdate")||this.a(this,"property","pubdate")||this.a(this,"property","article:published_at")||this.a(this,"property","article:published_time")||this.a(this,"property","og:pubdate")||this.ia(this,"itemprop","datePublished")||this.a(this,"name","date");return f.i(a)?a[0]:a},Z:function(){return this.a(this,"property","article:sr_author")||this.a(this,"property","article:author")||this.a(this,"property","author")||this.a(this,"name",
"author")},L:function(a,b){return this.a(this,"property",a)||this.a(this,"property",b)},ka:function(){return document.referrer},ca:function(a){a=this.a(this,"property","og:title")||this.a(this,"name","twitter:title")||document.title||a||!1;return f.i(a)?a[0]:a},B:function(a,b,c,d,e){a=a.m(b);b=[];for(var h=0;h<a.length;h++)a[h].getAttribute(c)===d&&b.push(a[h].getAttribute(e));if(b.length)return 1==b.length?b[0]:b},ha:function(a,b){return this.B(a,"link","rel",b,"href")},a:function(a,b,c){return this.B(a,
"meta",b,c,"content")},ia:function(a,b,c){return this.B(a,"time",b,c,"datetime")},Ma:function(a){var b=document.body,c=this.m("BODY")[0],d=this.m("HEAD")[0];b&&b.contains(a)?b.removeChild(a):c&&c.contains(a)?c.removeChild(a):d&&d.contains(a)&&d.removeChild(a);return a},V:function(a){var b=this,c=document.createElement("script");c.type="text/javascript";c.setAttribute("async",!0);c.setAttribute("name","memo");c.setAttribute("id","memo-script");c.src=a;k.info(a);this.D(function(){setTimeout(function(){b.m("HEAD")[0].appendChild(c)},
1)});return c},c:[],ready:!1,flush:function(){var a=this.c.shift();for(this.ready=!0;a;)a(),a=this.c.shift()},D:function(a){function b(){/loaded|interactive|complete/.test(document.readyState)?c.flush():setTimeout(b,500)}var c=this;this.ready?(this.c.push(a),this.flush()):document.documentElement.doScroll?window.self===window.top?function e(){if(!document.uniqueID&&document.expando)return this.c.push(a);try{document.documentElement.doScroll("left"),a()}catch(h){setTimeout(e,0)}}():(this.c.push(a),
b()):(this.c.push(a),b())},ta:function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c);return a},Ka:function(a,b,c){a.addEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c);return a},u:function(){return(window.pageYOffset?window.pageYOffset:document.documentElement?document.documentElement.scrollTop:0)-this.H},m:function(a){var b=[],c=0,d;if(!a)return[];if("string"!==typeof a)return[a];switch(a.charAt(0)){case "#":b.push(document.getElementById(a.substring(1)));
break;case ".":var e=document.getElementsByTagName("*");for(d=" "+a.substring(1)+" ";c<e.length;c+=1)a=(" "+e[c].className+" ").replace(/[\n\t\r]/g," "),-1<a.indexOf(d)&&b.push(e[c]);break;default:b=document.getElementsByTagName(a)}return b}},q={callbacks:{},C:function(a,b,c,d,e){d=d||function(){};if(/^https?:\/\/[\w\d\.]+\/*$/.test(c.url))k.info("Memo will not collect on home pages.");else{e||(e="cb");var h="cb"+f.xa(),m=this;c[e]="MEMO.API.callbacks."+h;e=f.N();"file://"===e&&(e="http://");c.v=
"v3.0.5";var p=x.encode(c);a=e+a+b+"?"+p;var t=g.V(a);c.test_mode&&console.log(a);m.callbacks[h]=function(y){setTimeout(function(){t.parentNode&&t.parentNode.removeChild(t)},0);d(y);try{delete m.callbacks[h]}catch(B){m.callbacks[h]=null}}}}},r={R:{},O:function(a){var b=document.cookie||"",c=this.R[a];c||(c=a.replace(/([.*+?\^=!:${}()|\[\]\/\\])/g,"\\$1"),c=new RegExp("(?:^|;)\\s?"+c+"=(.*?)(?:;|$)","i"),this.R[a]=c);return(a=b.match(c))&&decodeURIComponent(a[1])},F:function(a,b,c,d){var e=
"",h="; Secure; SameSite=None";c&&(e="; expires="+c.toGMTString());d&&(h="");document.cookie=a+"="+b+e+h+"; path=/"},Ha:function(a){this.F(a,"",new Date(1982,5,13))}},n={},z={X:function(a){var b;var c=f.G(a);c.authors&&(c.authors=f.A(c.authors));c.channels&&(c.channels=f.A(c.channels));c.tags&&(c.tags=f.A(c.tags));c.date&&"string"!==typeof c.date&&(c.date=c.date.toString());c.referrer=""==c.ref_url?"":this.S(c.referrer);c.ref_url=this.S(c.ref_url);c.page_url=c.page_url||window.location.toString();
c.uid?c.uid=c.uid:(b=this.ma())&&(c.uid=b);c.url&&(c.url=this.ya(c.url),a.url=c.url);return c},S:function(a){""!==a&&(a=a||g.ka());return a},ma:function(){return r.O("__srui")},ya:function(a){if(0===a.indexOf("http%253A")||0===a.indexOf("https%253A"))a=decodeURIComponent(a);if(0===a.indexOf("http%3")||0===a.indexOf("https%3"))a=decodeURIComponent(a);return a}},u={La:!1,Ja:!0,f:0,T:5E3,Ea:12E5,interval:null,reset:function(){g.H=g.u();window.clearInterval(this.interval)},track:function(a){var b=this,
c;b.interval=setInterval(function(){g.isVisible&&(b.f+=b.T);b.U()&&(b.f=0);c=f.G(a);c.t=b.f;c.e=b.na()?5E3:0;c.s=g.u();0===c.pid&&(c.pid="000000000000000000000000");g.isVisible&&!b.U()&&b.Fa(c)&&0<c.e&&(b.f=0,q.C("elsa.memoinsights.com","/t",c));b.qa=g.g.x;b.ra=g.g.y;b.pa=g.u()},b.T)},na:function(){return!0!==this.ga?this.ga=!0:this.qa!==g.g.x||this.ra!==g.g.y||this.pa!==g.u()?!0:!1},U:function(){return this.f>=this.Ea},Fa:function(a){return a.url&&a.pid}},l=f.va,v={o:[],data:{},response:null,options:null,
Na:!1,b:function(a,b){this.reset();this.options=b;this.response=a;var c=this;g.D(function(){c.height=c.ja();c.l||(c.l=function(){c.I()});n.manual_scroll_depth?c.wa():c.W()})},W:function(){"undefined"!==typeof document.addEventListener?document.addEventListener("scroll",this.l,!1):window.attachEvent("onscroll",this.l);this.I()},wa:function(){"undefined"!==typeof document.removeEventListener?document.removeEventListener("scroll",this.l,!1):window.detachEvent("onscroll",this.l)},I:function(){var a=this.la()+
Math.min(document.documentElement.clientHeight,window.innerHeight||0),b=0;a>=this.height?b=l[3]:b=a/this.height*100;97<=b?this.j(l[3]):b>=l[2]?this.j(l[2]):b>=l[1]?this.j(l[1]):b>=l[0]&&this.j(l[0])},ja:function(){if(n.content_height)var a=n.content_height;else{a=document.body;var b=document.documentElement;a=Math.max(a.scrollHeight,a.offsetHeight,b.clientHeight,b.scrollHeight,b.offsetHeight)}return a},la:function(){var a="CSS1Compat"===(document.compatMode||"");return void 0!==window.pageYOffset?
window.pageYOffset:a?document.documentElement.scrollTop:document.body.scrollTop},j:function(a){this.data={};f.contains(l,a)?f.contains(this.o,a)||(this.Aa(a),this.response.csd?this.za():k.info("[info] scroll depth not activated, not sending data")):k.error("[error] Invalid amount please send scroll depths of only: 25, 50, 75 or 100")},Aa:function(a){var b;for(b=0;b<l.length;b+=1){var c=l[b];a>=c&&!f.contains(this.o,c)&&(this.o.push(c),this.data[c]=!0,k.info("[info] sending scrollDepth of: "+c))}},
ua:function(){return f.sa({event:"csd",sd:this.data},this.options)},za:function(){if(!this.response.error){var a=this.ua();q.C("elsa.memoinsights.com","/event",a)}},reset:function(){this.o=[]}},A={track:function(a){var b=this;0===a.pid&&(a.pid="000000000000000000000000");q.C("elsa.memoinsights.com","/n",a,function(c){v.b(c,a);c.error?k.error("MEMO-ERROR: "+c.error.code+" - "+c.error.message):c.uid&&b.Da(c.uid)})},Da:function(a,b){r.F("__srui",a,new Date(2042,5,13),b)}},w={Ia:{},w:{},K:!1,b:function(){try{g.b();var a=
window.__memo_config;r.O("__srret")?this.P=!0:this.P=!1;r.F("__srret","1",new Date(2042,5,13));this.J(a)}catch(b){g.D(function(){k.Ba(b)})}},J:function(a){if(a){n=a;this.w=f.G(n);this.w.r=this.P;var b=this.w.ajax&&this.K;b||(a.url=a.url||g.ea());a.url?(k.b(a.ignore_errors),b&&(a.hasOwnProperty("ignore_metadata")||(a.ignore_metadata=!0),a.page_url=a.ref_url=a.referrer=a.url),a.title||(a.title=g.ca(a.url)),a.date||(a.date=g.aa()||f.Y(a.url)),a.tags||(b=g.L("article:sr_tag","article:tag"))&&(a.tags=
b),a.channels||(b=g.L("article:sr_section","article:section"))&&(a.channels=b),a.authors||(b=g.Z())&&(a.authors=b),u.reset(),a=z.X(a),A.track(a),u.track(a),this.K=!0):k.error("MEMO-ERROR: 100 - Missing url")}else k.error("Params not passed to collect")}};return{API:q,debug:k,setLogLevel:function(a){k.Ca(a)},collect:function(a){w.J(a)},init:function(){w.b()},stop:function(){u.reset()},scrollDepthReached:function(a){v.j(a)}}}();window.MEMO.init();
